### ISSUE TITLE
Subroutine Text::Template::XXX redefined at Text/Template.pm line 570

### ISSUE THREAD

**Issue by van-de-bugger** [mschout/perl-text-template#10]
Consider test case:

    #!/usr/bin/perl

    use Text::Template;

    my $t1 = Text::Template->new( package => 'MY', type => 'STRING', source => '' );
    $t1->fill_in( package => 'MY', hash => { include => sub { 'XX'; }, } );

    my $t2 = Text::Template->new( package => 'MY', type => 'STRING', source => '' );
    $t2->fill_in( package => 'MY', hash => { include => sub { 'XX'; }, } );

Being run with `Text::Template` 1.45, 1.46, and 1.47, it finishes with *no* warnings. Being run with 1.48, 1.49, 1.50, it causes warning:

    Subroutine Text::Template::include redefined at .../Text/Template.pm line 564.

1.51 gives similar result but line number slightly differs:

    Subroutine Text::Template::include redefined at .../Text/Template.pm line 570.

This regression in `Text::Template` causes [test failures](http://matrix.cpantesters.org/?dist=Dist-Zilla-Plugin-Templates%20v0.6.4) in `Dist::Zilla::Plugin::Templates`.

**Comment by van-de-bugger** [comment]
Looks like the regression was introduced by [this commit](https://github.com/mschout/perl-text-template/commit/c5bbd6df0f74398a4c584a0daaeb533f8d234574). The fix is trivial: after 

    no strict 'refs';

in line 560 should also be 

    no warning 'redefine';

**Comment by mschout** [comment]
Thanks!  Fixed in v1.52 which has just been uploaded to PAUSE
