### ISSUE TITLE
Text::Template 1.48,1.49 breaks Dist::Milla

### ISSUE THREAD

**Issue by skaji** [mschout/perl-text-template#8]
Text::Template 1.48,1.49 breaks [Dist::Milla](https://metacpan.org/release/Dist-Milla)'s `milla new` command:

```console
$ milla new Foo
[DZ] making target dir /Users/skaji/src/github.com/miyagawa/Dist-Milla/Foo
[Milla::MintFiles] Filling in the template returned undef for:
[Milla::MintFiles] Revision history for {{ $dist->name }}
[Milla::MintFiles]
[Milla::MintFiles] {{ '{{$NEXT}}' }}
[Milla::MintFiles]         - Initial release
...
$ echo $?
255
```

The following script shows difference between 1.46 and 1.49, which actually breaks Dist::Milla.
```perl
# test.pl
use strict;
use warnings;
use Text::Template;

printf "perl %s, Text::Template %s\n", $^V, Text::Template->VERSION;

my $tmpl = Text::Template->new(
    TYPE       => 'STRING',
    SOURCE     => q| {{ '{{$NEXT}}' }} |,
    DELIMITERS => [ '{{', '}}' ],
);

my $content = $tmpl->fill_in;
print "Result: ", $content // '(undef)', "\n";
```

```console
$ perl test.pl
perl v5.26.1, Text::Template 1.46
Result:  {{$NEXT}}

$ perl test.pl
perl v5.26.1, Text::Template 1.47
Result:  {{$NEXT}}

$ perl test.pl
perl v5.26.1, Text::Template 1.48
Result: (undef)

$ perl test.pl
perl v5.26.1, Text::Template 1.49
Result: (undef)
```

**Comment by mschout** [comment]
72f457f73c62dba429b76bdf1eeee7a822a65052 is the first bad commit
commit 72f457f73c62dba429b76bdf1eeee7a822a65052
Author: Michael Schout <mschout@gkg.net>
Date:   Wed Jan 3 16:57:40 2018 -0600

    allow start/end delimiters to be identical
    
    This allows the start/end delimiters to be identical.
    E.g.: DELIMITERS => [ '@@', '@@' ] now works.
    
    Fixes RT #46639

:100644 100644 2e425e38fcf676dab990310ed27fd146da2b7e72 8e62fbfef8a626ddacab4abbfd0baaead088e97c M	Changes
:040000 040000 9ccc2a5998632aae2e6588bf7e482e324ca8335d 1e6f9c8b7957882f587a7a00146bc8f2b6b2e6d0 M	lib
:040000 040000 6368e686dcec952a20c704dd06b04a1e3a7088be d8fe7ca3568c622eb4dfc6838441a35bb511a5a5 M	t

**Comment by mschout** [comment]
Basically the way that change was implemented breaks cases where you have nested tags such as this example.

Given the severity of the breakage, and how recently this was added, I'm inclined to revert it and release a version without the same start/end tag feature for now and revisit that in the future.

**Comment by skaji** [comment]
@mschout Thanks for looking into this.

> I'm inclined to revert it and release a version without the same start/end tag feature for now and revisit that in the future.

I agree.

**Comment by mschout** [comment]
reverted and released in v1.50, just released.

**Comment by mschout** [comment]
sorry for the multi-hour delay.  U-verse sh*t the bed here. :)

**Comment by skaji** [comment]
@mschout I confirmed that `milla new` works fine with Text::Template 1.50.
I'm closing this issue. Thanks!
